# Generated by Django 2.2.3 on 2019-09-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoas',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
