# Generated by Django 2.2.3 on 2019-09-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0002_auto_20190924_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabalhoGeladeira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dia')),
                ('geladeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacao.Geladeira')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacao.Pessoas')),
            ],
        ),
        migrations.CreateModel(
            name='TrabalhoFogao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dia')),
                ('fogao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacao.MicroEFogao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacao.Pessoas')),
            ],
        ),
    ]
