# Generated by Django 2.2.3 on 2019-09-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0004_geladeira_numgeladeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhogeladeira',
            name='dia_fim',
            field=models.DateField(default='1999-01-01', verbose_name='último dia'),
        ),
        migrations.AlterField(
            model_name='geladeira',
            name='numGeladeira',
            field=models.IntegerField(verbose_name='Número da Geladeira'),
        ),
    ]
